### ISSUE TITLE
what's the 'wd_search'

### ISSUE THREAD

**Issue by jackaduma** [Ebiquity/CASIE#13]
In the parseJsontoFeatures.py(line 25 and 212), what’s the ”wd_search” ? I google nothing about it. I guess that’s your code. Would you like sharing your code to me ? Thank you very much.

**Comment by finin** [comment]
I'll try to integrate it in, but for now, see wd_search_cyber.py in the repository https://github.com/Ebiquity/wd_cyber.  This requires wd_search.py in the same repo.
