### ISSUE TITLE
Requirements installation fails

### ISSUE THREAD

**Issue by GBR-613** [Ebiquity/CASIE#20]
Requirements installation (pip install -r requirements.txt) fails due to packages versions that can not be found and packages versions conflicts.

For example (copied from pip output):

ERROR: Cannot install -r requirements.txt (line 1) and numpy==1.17.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.17.2
    bert-embedding 1.0.1 depends on numpy==1.14.6

The version 1.0.1 of bert-embedding appears to be the only present in pypi.org. Therefore I removed the version of numpy to let pip choose the best one. But it caused another problem:
tensorflow-gpu 2.0.0 requires numpy<2.0,>=1.16.0, but you have numpy 1.14.6 which is incompatible.

Also,  I could not install tensorflow-gpu 2.0.0 because pip said there is no compatible wheel.  Fortunately, it succeeded when I downloaded the wheel to my local file system and installed it from there. But, in addition to the mentioned above, pip complains on the following:

tensorflow-gpu 2.0.0 requires keras-applications>=1.0.8, but you have keras-applications 1.0.7 which is incompatible.
tensorflow-gpu 2.0.0 requires tensorboard<2.1.0,>=2.0.0, but you have tensorboard 1.13.1 which is incompatible.
tensorflow-gpu 2.0.0 requires tensorflow-estimator<2.1.0,>=2.0.0, but you have tensorflow-estimator 1.13.0 which is incompatible.

keras-contrib is not present in pypi.org.  It can be installed from Github, but the specified version is not found.  (Actually, no specific version can be found in that repository.)
If the current version is OK, could you please replace the respective line in requirements.txt with the following:
git+https://git@github.com/keras-team/keras-contrib.git
BTW, the repository README now says they are migrating to tensorflow/addons.  If it's OK to install it instead, please suggest which version to take.

Also, pywikibot==3.0.dev0 is not found in pypi.org anymore.  I guess the most close would be pywikibot==3.0.20170403, but its installation fails, because the respective wheel meta-data says it is 3.0.dev0 that is different from the wheel name.

Also, requests==2.21.0 requires version of urllib3 different from the specified (1.25.7)

I am using Python 3.6.13 on Ubuntu 20.04.  Do you recommend another version of Python?  I might be wrong, but if I remember correctly, some of the listed packages versions need v3.6 specifically.

**Comment by JuliusNmn** [comment]
I'm also having trouble getting it to run. Did using python v3.6 solve your problems?

**Comment by JuliusNmn** [comment]
If I use python 3.6, pip finds all packages and the tool runs. Make sure that pip uses 3.6
