### ISSUE TITLE
"from tensorflow import set_random_seed" fails

### ISSUE THREAD

**Issue by GBR-613** [Ebiquity/CASIE#21]
The line "from tensorflow import set_random_seed" appearing in the following files:

      - nug_arg_detection.py 
      - parseJsontoFeatures.py 
      - prepare.py 
      - x2index.py 
      - nug_arg_detection_bert.py 

causes the following error:
ImportError: cannot import name 'set_random_seed'

In TensorFlow2, tf.random.set_seed() should be used instead.

Are you using TensorFlow1, in contrary to what requirements.txt says?

**Comment by staneeya** [comment]
I think you are correct. The code is a little bit old.
