### ISSUE TITLE
wd_search not found

### ISSUE THREAD

**Issue by GBR-613** [Ebiquity/CASIE#22]
The line "import wd_search" in parseJsontoFeatures.py fails with the following error:
ModuleNotFoundError: No module named 'wd_search'

In which package the module is present?  Please suggest.

**Comment by HuangZhenyang** [comment]
@GBR-613 Maybe you can find the solution in [https://github.com/Ebiquity/CASIE/issues/4](https://github.com/Ebiquity/CASIE/issues/4) and [https://github.com/Ebiquity/CASIE/issues/13](https://github.com/Ebiquity/CASIE/issues/13).

**Comment by GBR-613** [comment]
@HuangZhenyang thanks a lot

**Comment by HuangZhenyang** [comment]
@GBR-613 no problem.
