### ISSUE TITLE
.ner.json file format

### ISSUE THREAD

**Issue by JuliusNmn** [Ebiquity/CASIE#25]
Hi,
I was able to create .content.json (using stanford corenlp) and content.nostop.label files (with [this](https://github.com/josephKhoury95/CASIE-Corpus---helper-code) repo). Now the program is looking for .ner.json files. Could you please provide a sample of these files so I know how to generate them? Many thanks in advance.

**Comment by staneeya** [comment]
[5.ner.json.txt](https://github.com/Ebiquity/CASIE/files/7040125/5.ner.json.txt)
The file is the sample of ".ner.json". Just rename it by removing ".txt".
Hope it helps.
