### ISSUE TITLE
ModuleNotFoundError: No module named 'wd_search'

### ISSUE THREAD

**Issue by NellyLuo** [Ebiquity/CASIE#4]
### Question and ask for help
There is an ModuleNotFoundError: No module named 'wd_search', and I didn't find related package in PyPi. Are the related functions renamed?

**Comment by staneeya** [comment]
You can find "wd_search" from https://github.com/Ebiquity/wd_cyber .

**Comment by skyWalker1997** [comment]
@staneeya  Hello staneeya! I am interesting in this project. Could you please offer some introduction or guideline about how to run this work properly. Thanks a lot!
