### ISSUE TITLE
how to generate .ner.json files

### ISSUE THREAD

**Issue by FU626** [Ebiquity/CASIE#47]
Does anyone know how to generate **.ner.json** files? 
I still don't understand how to generate the files after looking that example.

I don't know how to obtain the "casetype".
And the results I generated using Wikidata and DBpedia spotlight are not quite consistent with the example.
![图片](https://github.com/Ebiquity/CASIE/assets/62916841/d344d63f-d12f-44d1-aa3d-903feed9faf6)

**Comment by staneeya** [comment]
.ner.json can be generated using Stanford coreNLP. The inconsistency might be caused from the outdate of data compared to the votality of Wikidata or DBpedia.

**Comment by FU626** [comment]
> .ner.json can be generated using Stanford coreNLP. The inconsistency might be caused from the outdate of data compared to the votality of Wikidata or DBpedia.

Thank you a lot !
