### ISSUE TITLE
how to find or generate the . pkl file?

### ISSUE THREAD

**Issue by FU626** [Ebiquity/CASIE#49]
I'm very sorry that I have encountered a new problem. 

I don't know how to generate the `. pkl` file in `nug_arg_detection_bert.py`. Are these files generated through the BERT model? 
Can you give me an example or some advice?

![图片](https://github.com/Ebiquity/CASIE/assets/62916841/d8593087-4efa-41ca-a754-2874e1d3010c)

**Comment by morris891205** [comment]
excuse me, I wonder if you successfully generate the "ner.json" files. If you did, would you please tell me how you generate them or share the code? thank you so much!

**Comment by staneeya** [comment]
It is the word vector extracted from BERT and saved in a pickle file for each input file. I just uploaded 'bert_to_pickle.py' which do the job.
