### ISSUE TITLE
Was CASIE manually annotated ?

### ISSUE THREAD

**Issue by thangld201** [Ebiquity/CASIE#55]
Hi @staneeya @finin, thank you very much for the works!

I only saw definitions of event types and arguments in the paper, but how was the annotations obtained ? Was it manually annotated or automatically aligned through heuristics ?

**Comment by finin** [comment]
CASIE used manual annotations.

--
Tim Finin, Computer Science & Electrical Engineering, Univ. Maryland
Baltimore County
1000 Hilltop Circle, Baltimore, MD 21250.  http://umbc.edu/~finin,
***@***.***
