### ISSUE TITLE
Can't find content.nostop.label and .content.json

### ISSUE THREAD

**Issue by nansunsun** [Ebiquity/CASIE#8]
Does anyone know about how to get content.nostop.label and .content.json or .ner.json which are for train and test input? Thanks in advance. Cheers.

**Comment by josephKhoury95** [comment]
Any update on this?
Any help is highly appreciated. Thank you.

**Comment by HuangZhenyang** [comment]
I am stuck on this too. I don't know what data is like in the file “content.nostop.label”. Any ideas? Thx.

**Comment by josephKhoury95** [comment]
> I am stuck on this too. I don't know what data is like in the file “content.nostop.label”. Any ideas? Thx.

I invite you to check a [helper code here](https://github.com/josephKhoury95/CASIE-Corpus---helper-code) for Inside, Outside, Beginning (IOB) tagging format and linguistic annotations using spaCy library for the CASIE corpus. [CASIE work is cited in the repository].

**Comment by HuangZhenyang** [comment]
@josephKhoury95 
OK, I'll check that. Thank you so much, you are so nice. :D

**Comment by Atleastihaveme** [comment]
> > I am stuck on this too. I don't know what data is like in the file “content.nostop.label”. Any ideas? Thx.
> 
> I invite you to check a [helper code here](https://github.com/josephKhoury95/CASIE-Corpus---helper-code) for Inside, Outside, Beginning (IOB) tagging format and linguistic annotations using spaCy library for the CASIE corpus. [CASIE work is cited in the repository].

Thx! How can I get the file with content.nostop.label and .content.json by [helper code]?And Would you know what is the trainfile and testfile of CASIE?Any help is highly appreciated. Thank you!

**Comment by josephKhoury95** [comment]
> Thx! How can I get the file with content.nostop.label and .content.json by [helper code]?And Would you know what is the trainfile and testfile of CASIE?Any help is highly appreciated. Thank you!

@Atleastihaveme, I gave up the provided code. 
I ended up using  CASIE corpus only and annotated the corpus using the helper code. 
Then, I trained a CRF and a Bidirectional LSTM with CRF on my own.

**Comment by Atleastihaveme** [comment]
> > Thx! How can I get the file with content.nostop.label and .content.json by [helper code]?And Would you know what is the trainfile and testfile of CASIE?Any help is highly appreciated. Thank you!
> 
> @Atleastihaveme, I gave up the provided code.
> I ended up using CASIE corpus only and annotated the corpus using the helper code.
> Then, I trained a CRF and a Bidirectional LSTM with CRF on my own.

 Thank you so much, you are so nice！Could you please share your code with me? I' m studying this now,and can't find useful resourse. I will be appreciate of it very much!

**Comment by josephKhoury95** [comment]
> Thank you so much, you are so nice！Could you please share your code with me? I' m studying this now,and can't find useful resourse. I will be appreciate of it very much!

I followed this [article](https://www.aitimejournal.com/@akshay.chavan/complete-tutorial-on-named-entity-recognition-ner-using-python-and-keras). 
Also, the author of the article provide his GitHub code.

**Comment by Atleastihaveme** [comment]
> > Thank you so much, you are so nice！Could you please share your code with me? I' m studying this now,and can't find useful resourse. I will be appreciate of it very much!
> 
> I followed this [article](https://www.aitimejournal.com/@akshay.chavan/complete-tutorial-on-named-entity-recognition-ner-using-python-and-keras).
> Also, the author of the article provide his GitHub code.

Thx, you are really so nice! Thanks again!

**Comment by staneeya** [comment]
Hi guys,

Sorry for the late reply. I have a lot on my plate right now.
The content.json can be produced using Stanford CoreNLP . Below is an example.

[4.content.json.zip](https://github.com/Ebiquity/CASIE/files/6523786/4.content.json.zip)

Another example for  content.nostop.label which can easily produce by a simple script.
[4.content.nostop.label.zip](https://github.com/Ebiquity/CASIE/files/6523819/4.content.nostop.label.zip)

Hope it helps.

**Comment by HuangZhenyang** [comment]
@staneeya Thanks a million. Hope everything goes well with your work. :D

**Comment by Atleastihaveme** [comment]
Thanks a lot！ :D
